# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(479, 329)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("QPushButton{\n"
"text-align: left;    /* buton içindeki yazıyı sola yaslamak için kullandım. */\n"
"padding-left: 9em;        /*sola yaslanan yazıyı birazcık sağdan başlaması için eklendi. kısaca butonlar alt alta gelince yazılar ortalı başladığı için iyi görünmüyordu yukardaki iki ayarla soldan başlatıp aynı hizaya alıp birazcık ortaya doğru almış oldum*/\n"
"margin: 0px;\n"
"min-height: 2em;\n"
"border-radius: 0px;\n"
"border-style: solid;\n"
"font: bold 14px;\n"
"color: rgb(201, 243, 201);\n"
"background-color: rgb(39, 39, 39);\n"
"border-color: rgb(47, 172, 126);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border-left-width: 20px;\n"
"border-color:rgb(71, 180, 111)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"border-color: rgb(168, 186, 253);\n"
"    background-color:rgb(22, 22, 22);\n"
"    color:  rgb(201, 243, 201);\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QToolButton{\n"
"min-height: 20px;\n"
"min-width: 20px;\n"
"background-color: initial;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"background-color: rgb(108, 0, 0);\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"background-color: rgb(247, 247, 222);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QLabel{\n"
"min-height: 30px;\n"
"min-width: 30px;\n"
"font: bold 14px;\n"
"color: rgb(201, 243, 201);\n"
"}\n"
"\n"
"")
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_icon = QtWidgets.QLabel(self.frame)
        self.label_icon.setText("")
        self.label_icon.setObjectName("label_icon")
        self.horizontalLayout.addWidget(self.label_icon)
        self.label_title = QtWidgets.QLabel(self.frame)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButton_developer = QtWidgets.QToolButton(self.frame)
        self.toolButton_developer.setText("")
        self.toolButton_developer.setObjectName("toolButton_developer")
        self.horizontalLayout.addWidget(self.toolButton_developer)
        self.toolButton_sound = QtWidgets.QToolButton(self.frame)
        self.toolButton_sound.setText("")
        self.toolButton_sound.setObjectName("toolButton_sound")
        self.horizontalLayout.addWidget(self.toolButton_sound)
        self.toolButton_move = QtWidgets.QToolButton(self.frame)
        self.toolButton_move.setText("")
        self.toolButton_move.setObjectName("toolButton_move")
        self.horizontalLayout.addWidget(self.toolButton_move)
        self.toolButton_minimize = QtWidgets.QToolButton(self.frame)
        self.toolButton_minimize.setText("")
        self.toolButton_minimize.setObjectName("toolButton_minimize")
        self.horizontalLayout.addWidget(self.toolButton_minimize)
        self.toolButton_close = QtWidgets.QToolButton(self.frame)
        self.toolButton_close.setText("")
        self.toolButton_close.setObjectName("toolButton_close")
        self.horizontalLayout.addWidget(self.toolButton_close)
        self.verticalLayout.addWidget(self.frame)
        self.pushButton_selectfile = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_selectfile.sizePolicy().hasHeightForWidth())
        self.pushButton_selectfile.setSizePolicy(sizePolicy)
        self.pushButton_selectfile.setObjectName("pushButton_selectfile")
        self.verticalLayout.addWidget(self.pushButton_selectfile)
        self.pushButton_save = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.pushButton_save)
        self.pushButton_start = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.verticalLayout_2.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "AWD TO OBJ"))
        self.pushButton_selectfile.setText(_translate("MainWindow", "SELECT FILE"))
        self.pushButton_save.setText(_translate("MainWindow", "DIRECTORY TO SAVE"))
        self.pushButton_start.setText(_translate("MainWindow", "START CONVERSION"))
